[project]
name = "mode-connectivity"
version = "0.1.0"
description = "Reproducibility code for scaling symmetries and neural-network mode connectivity"
authors = [
    {name = "Maciej Lodzinski",email = "mf.lodzinski@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10,<3.12"
dependencies = [
    "torch",
    "torchvision",
    "torchviz",
    "hydra-core",
    "omegaconf",
    "numpy",
    "scipy",
    "matplotlib",
    "pillow (>=12.0.0,<13.0.0)",
    "plotly (>=6.5.2,<7.0.0)",
]

[tool.poetry]
packages = [{include = "mode_connectivity", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
