defaults: []

experiment_name: "external_sinkhorn_original_train_vgg16_mnist"
output_root: "results/vgg16/mnist/original_sinkhorn_vgg16_train"

data_path: "./data"
use_small_dataset: false
validation_size: 5000
image_size: 32
num_workers: 4
split_seed: 1

model_a_seed: 0
model_b_seed: 1

train_batch_size: 1000
eval_batch_size: 1000
train_epochs: 50
optimizer_name: "adamw"
train_lr: 0.05
weight_decay: 5e-4

early_stopping_patience: 10
min_delta: 0.0005
log_interval: 1

device: "auto"
