init_start: "results/vgg16/cifar10/endpoints/standard/seed0/checkpoints/checkpoint-200.pt"
init_end: "results/vgg16/cifar10/endpoints/standard/seed1/checkpoints/checkpoint-200.pt"
output_dir: "results/vgg16/cifar10/advanced_geometry/random_plane_random/seed0-seed1"

dataset: "CIFAR10"
model: "VGG16"
transform: "VGG"
use_test: true
data_path: "./data"

# Curve settings
curve: "PolyChain"
num_bends: 3
fix_start: true
fix_end: true

# Training settings
epochs: 150
lr: 0.015
momentum: 0.9
wd: 0.0005

# Totally random plane projection
project_random_plane: true
random_plane_seed: 42
random_anchor: true  # Random anchor point
