defaults: []

experiment_name: "garipov_vgg16_mnist_endpoints"

output_root: "results/vgg16/mnist/endpoints/standard"

dataset: "MNIST"
data_path: "./data"
transform: "VGG"
model: "VGG16"

epochs: 50
save_intermediate: true
save_freq: 25
lr: 0.05
momentum: 0.9
wd: 5e-4
batch_size: 128
num_workers: 4
use_test: true

seeds: [0, 1]

use_wandb: false
project_name: "thesis-mode-connectivity"
